version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:5000"
  python:
    build:
      context: .
      dockerfile: docker/python.Dockerfile
    ports:
      - "8000:8000"
